### PR TITLE
Normalizing locations #69

### PR DESCRIPTION
**Pull request by erinnachen**
This normalizes the information from location column on the jobs table. Location is now implemented as a separate model with a single field, name.

* Added a migration to move current location information into a different column called old_location.
* Added location model
* Created a location_id column on the Jobs model to refer to a single location: Locations have many jobs and jobs belong to a location
* Changed the job factory to reflect the association with location
* Added a location factory
* JobFetcher now expects that the entry hash has a location field (similar to category), removed location from the jobs field
  * Raw entry in tests modified to reflect this change.
* Added additional tests for job fetcher
* All feature/model tests pass

Outstanding issues:
[ ] Waiting on #37 to be sorted out to convert old_locations to a location (rake task)
[ ] After above is handled, a migration will remove old_locations from the jobs table
[ ] Looking at some of the entries, we will have to smartly parse the locations. One challenge is that foreign countries may come in as full descriptions and from another service is referred by abbreviation: e.g. London, UK and London, United Kingdom and these should be parse to the same location. Another example is dealing with the fact that some US locations also have US or USA appended to the end. Another thing to think about is that multiple locations may be parsed from a job listing.

Any thoughts? @rrgayhart @NickyBobby @brennanholtzclaw @hhoopes

### CODE REVIEW

**Comment by hhoopes** [comment]
Responding here first, before looking at code line items. 

Some of this will be easier once we're able to scrape a location, but your experience does suggest that we will need to add a country column, and if none is given, assume a default of the US. Additionally we will have to consider making a job able to have_many locations, even if most jobs will only have one. 

I looked briefly to see if there was a location standardizing gem for Ruby, but didn't quickly see what I was looking for.  I guess a library of common city/country abbreviations that will output a single reference. Surely this must be a solved problem to some extent. Maybe we can tag a mentor if this gets to be a handful? Or perhaps this is simply a mechanical turk-style problem.

**Comment by erinnachen** [comment]
One other discussion @NickyBobby and I had was that I don't know was really kosher was this change of column name to preserve the old data while then having the ability to create the association jobs.location.

**Comment by brennanholtzclaw** [comment]
I like the solution here, but as you say in your comment above, I don't know about the "kosher-ness" of changing the current column name? Could we perhaps tag items currently in the database with a known piece of information so that they could be sorted out at a later date? That was everything is on the same page, but we know which ones have the "bad" locations. 

That being said, I like the changes to the services and the use of the serializer to keep everything looking the same. I'm comfortable with this solution, despite not being positive whether or not it's "best practice".

**Comment by NickyBobby** [comment]
I merged our current master on to this branch and there were a couple merge conflicts. I resolved the merge conflicts, but we still have 45 tests failing. I would be willing to go through the tests if someone wants to help me. This is also going to change the way we make queries and stuff so they'll be some changes there as well. We can talk about it more in person tomorrow. @hhoopes @brennanholtzclaw @erinnachen @rrgayhart

**Comment by erinnachen** [comment]
@NickyBobby This branch has location on a separate table, so the factory for jobs is not working. This is your current factory for job:
```ruby
factory :job do
    sequence(:title, 1) { |n| [Faker::Company.profession, n].join }
    description { Faker::Company.bs }
    url { Faker::Internet.url }
    location { "New York, NY" }
    posted_date { Faker::Date.between(2.days.ago, Date.today) }
    raw_technologies { [[Faker::Hacker.adjective, Faker::Hacker.noun].join(' '),
                      [Faker::Hacker.adjective, Faker::Hacker.noun].join(' '),
                      Faker::Hacker.abbreviation] }
    remote false
    company
  end
```
I think a bunch of problems will be removed if you use the location factory by association, i.e. instead of `location { "New York, NY" }` it should be just `location`

**Comment by erinnachen** [comment]
@NickyBobby It might be helpful to not try to coerce the tests with old location. Perhaps tackling the moving of old_locations onto the locations table and then coming back to fix the tests is a less redundant approach.

**Comment by NickyBobby** [comment]
I was able to get all of the tests to pass. This merge should change all the current locations over to old_locations and then normalizing locations to a separate table. Should I go ahead and make a rake task to update all the past job locations over to the new table? @erinnachen @hhoopes @rrgayhart @brennanholtzclaw

**Comment by NickyBobby** [comment]
Also I just noticed there are merge conflicts. I'll take care of that now.

**Comment by hhoopes** [comment]
@NickyBobby it's ready for you

**Comment by NickyBobby** [comment]
If no one has any objections I'll merge this branch now. @hhoopes @brennanholtzclaw @rrgayhart

**Pull request merged**
