### PR TITLE
Delete lookingforme subfolder that got randomly added in last commit

### PR DESCRIPTION
**Pull request by ksk5280**

### CODE REVIEW

**Comment by cheljoh** [comment]
Interesting issue- the folder is empty so it's not doing anything. Get it out of hereerrree

**Comment by NickyBobby** [comment]
haha I thought that thing was weird. What is it? @cheljoh @ksk5280

**Comment by hhoopes** [comment]
Bizarre!

**Comment by cheljoh** [comment]
It originally contained Kimi's commit SHA1. Unclear.

**Pull request merged**
