### PR TITLE
Add /api/v1/jobs/:id endpoint

### LINKED ISSUE #77: Job Show Endpoint
Would like an endpoint to show individual jobs so we can access it using the id (api/v1/jobs/2). Thanks!

### PR DESCRIPTION
**Pull request by erinnachen**
* renders the job object with json
* the responders gem was not being used, so I did not pull it in
   * Should we try to follow the JSON API standards and use a gem like jsonapi-for-rails?

closes #77

### CODE REVIEW

**Comment by NickyBobby** [comment]
That's a very nice end point you got there! And a thorough test as well! Looks to me like it's ready to be merged. Unless anyone has any objections? @erinnachen @hhoopes @brennanholtzclaw

**Comment by hhoopes** [comment]
I think before we merge we need to address where we stand on JSON standards. I think this is another issue that comes down to what we're interested in learning and if someone is excited to try pushing this further. If we desperately need this endpoint, it's close enough and good enough to stand as-is.

**Comment by NickyBobby** [comment]
@hhoopes I would be willing to go a little further to make the JSON output exactly how we want it. Also it comes down to what the front end team needs. I know Brian wanted me to tweak the output a little bit. I'll talk to him tomorrow about it.

**Comment by hhoopes** [comment]
Cool, sounds good. I'll be looking for a new issue to pick up tomorrow too.

**Comment by cheljoh** [comment]
I'm personally fine with returning a Job object from the endpoint- that is all we really need.

**Comment by brennanholtzclaw** [comment]
I don't mean this to sound like a kicking the can down the road thing, but do we ever expect other people to handle this? 
I feel like if the future expectation is to open this up, using the JSON API standards is probably best practice that we should aim for. On the other hand, if this is just an endpoint that our front-end team needs, I don't see a point in making it too complicated.
I like API's, so I vote for doing it all verbose and JSON standard-y. It's just more work.
https://giphy.com/gifs/swamppeople-funny-cute-swamp-people-wG93amBJZiewE

**Comment by hhoopes** [comment]
We will have a meeting in an hour. I suggest we force the issue and decide then what course we want to take.

For the front-end team, urgency seems better, but if we decide not to use the JSON standard, no future module will use it.

**Comment by hhoopes** [comment]
Had to fix a conflict in routes, but tests are passing and the endpoint looks good. Will merge once Travis is done.

**Pull request merged**
