### PR TITLE
Search by location endpoint

### LINKED ISSUE #94: Endpoint for Searching By Location
New endpoint for searching jobs by location. Search should be fuzzy and case insensitive.

### PR DESCRIPTION
**Pull request by cheljoh**
@hhoopes @brennanholtzclaw @ksk5280 @NickyBobby 

Modified recent_jobs endpoint so it takes an optional parameter- location. The query is case insensitive and returns jobs that contain all or part of the location parameter. Added controller and model tests as needed.

Closes #94

### CODE REVIEW

**Comment by brennanholtzclaw** [comment]
Looks good to me. I'm willing to get this merged in if someone else signs off on it.

**Comment by hhoopes** [comment]
Is this not WIP then?

**Comment by cheljoh** [comment]
I wanted to test this endpoint in development from the front end to make sure I didn't want to modify the params or the JSON response, and everything appears to work! I'm ready for a merge @hhoopes @brennanholtzclaw

**Comment by hhoopes** [comment]
Tests look good, thanks cheljoh!

**Pull request merged**
